//SHOW ALL POSSIBLE CUSTOM CLICKS (CALLED PROGRAMMATICALLY ABOVE)
function customClicks() {
    EB.clickthrough('Cherokee 2017 Build and Price');
    EB.clickthrough('Cherokee 2017 View Incentives');
    EB.clickthrough('Cherokee 2017 Vehicle Homepage');
    EB.clickthrough('Cherokee 2017 Search Inventory');
    EB.clickthrough('Cherokee 2017 Find a Dealer');
    EB.clickthrough('Cherokee 2017 View Gallery');
    EB.clickthrough('Compass 2017 Build and Price');
    EB.clickthrough('Compass 2017 View Incentives');
    EB.clickthrough('Compass 2017 Vehicle Homepage');
    EB.clickthrough('Compass 2017 Search Inventory');
    EB.clickthrough('Compass 2017 Find a Dealer');
    EB.clickthrough('Compass 2017 View Gallery');
    EB.clickthrough('Grand_Cherokee 2017 Build and Price');
    EB.clickthrough('Grand_Cherokee 2017 View Incentives');
    EB.clickthrough('Grand_Cherokee 2017 Vehicle Homepage');
    EB.clickthrough('Grand_Cherokee 2017 Search Inventory');
    EB.clickthrough('Grand_Cherokee 2017 Find a Dealer');
    EB.clickthrough('Grand_Cherokee 2017 View Gallery');
    EB.clickthrough('Patriot 2017 Build and Price');
    EB.clickthrough('Patriot 2017 View Incentives');
    EB.clickthrough('Patriot 2017 Vehicle Homepage');
    EB.clickthrough('Patriot 2017 Search Inventory');
    EB.clickthrough('Patriot 2017 Find a Dealer');
    EB.clickthrough('Renegade 2017 Build and Price');
    EB.clickthrough('Renegade 2017 View Incentives');
    EB.clickthrough('Renegade 2017 Vehicle Homepage');
    EB.clickthrough('Renegade 2017 Search Inventory');
    EB.clickthrough('Renegade 2017 Find a Dealer');
    EB.clickthrough('Renegade 2017 View Gallery');
    EB.clickthrough('Wrangler 2017 Build and Price');
    EB.clickthrough('Wrangler 2017 View Incentives');
    EB.clickthrough('Wrangler 2017 Vehicle Homepage');
    EB.clickthrough('Wrangler 2017 Search Inventory');
    EB.clickthrough('Wrangler 2017 Find a Dealer');
    EB.clickthrough('Wrangler 2017 View Gallery');
    EB.clickthrough('Wrangler_Unlimited 2017 Build and Price');
    EB.clickthrough('Wrangler_Unlimited 2017 View Incentives');
    EB.clickthrough('Wrangler_Unlimited 2017 Vehicle Homepage');
    EB.clickthrough('Wrangler_Unlimited 2017 Search Inventory');
    EB.clickthrough('Wrangler_Unlimited 2017 Find a Dealer');
    EB.clickthrough('Wrangler_Unlimited 2017 View Gallery');
    EB.clickthrough('Cherokee 2018 Build and Price');
    EB.clickthrough('Cherokee 2018 View Incentives');
    EB.clickthrough('Cherokee 2018 Vehicle Homepage');
    EB.clickthrough('Cherokee 2018 Search Inventory');
    EB.clickthrough('Cherokee 2018 Find a Dealer');
    EB.clickthrough('Cherokee 2018 View Gallery');
    EB.clickthrough('Compass 2018 Build and Price');
    EB.clickthrough('Compass 2018 View Incentives');
    EB.clickthrough('Compass 2018 Vehicle Homepage');
    EB.clickthrough('Compass 2018 Search Inventory');
    EB.clickthrough('Compass 2018 Find a Dealer');
    EB.clickthrough('Compass 2018 View Gallery');
    EB.clickthrough('Grand_Cherokee 2018 Build and Price');
    EB.clickthrough('Grand_Cherokee 2018 View Incentives');
    EB.clickthrough('Grand_Cherokee 2018 Vehicle Homepage');
    EB.clickthrough('Grand_Cherokee 2018 Search Inventory');
    EB.clickthrough('Grand_Cherokee 2018 Find a Dealer');
    EB.clickthrough('Grand_Cherokee 2018 View Gallery');
    EB.clickthrough('Patriot 2018 Build and Price');
    EB.clickthrough('Patriot 2018 View Incentives');
    EB.clickthrough('Patriot 2018 Vehicle Homepage');
    EB.clickthrough('Patriot 2018 Search Inventory');
    EB.clickthrough('Patriot 2018 Find a Dealer');
    EB.clickthrough('Renegade 2018 Build and Price');
    EB.clickthrough('Renegade 2018 View Incentives');
    EB.clickthrough('Renegade 2018 Vehicle Homepage');
    EB.clickthrough('Renegade 2018 Search Inventory');
    EB.clickthrough('Renegade 2018 Find a Dealer');
    EB.clickthrough('Renegade 2018 View Gallery');
    EB.clickthrough('Wrangler 2018 Build and Price');
    EB.clickthrough('Wrangler 2018 View Incentives');
    EB.clickthrough('Wrangler 2018 Vehicle Homepage');
    EB.clickthrough('Wrangler 2018 Search Inventory');
    EB.clickthrough('Wrangler 2018 Find a Dealer');
    EB.clickthrough('Wrangler 2018 View Gallery');
    EB.clickthrough('Wrangler_Unlimited 2018 Build and Price');
    EB.clickthrough('Wrangler_Unlimited 2018 View Incentives');
    EB.clickthrough('Wrangler_Unlimited 2018 Vehicle Homepage');
    EB.clickthrough('Wrangler_Unlimited 2018 Search Inventory');
    EB.clickthrough('Wrangler_Unlimited 2018 Find a Dealer');
    EB.clickthrough('Wrangler_Unlimited 2018 View Gallery');
    EB.clickthrough('Cherokee 2019 Build and Price');
    EB.clickthrough('Cherokee 2019 View Incentives');
    EB.clickthrough('Cherokee 2019 Vehicle Homepage');
    EB.clickthrough('Cherokee 2019 Search Inventory');
    EB.clickthrough('Cherokee 2019 Find a Dealer');
    EB.clickthrough('Cherokee 2019 View Gallery');
    EB.clickthrough('Compass 2019 Build and Price');
    EB.clickthrough('Compass 2019 View Incentives');
    EB.clickthrough('Compass 2019 Vehicle Homepage');
    EB.clickthrough('Compass 2019 Search Inventory');
    EB.clickthrough('Compass 2019 Find a Dealer');
    EB.clickthrough('Compass 2019 View Gallery');
    EB.clickthrough('Grand_Cherokee 2019 Build and Price');
    EB.clickthrough('Grand_Cherokee 2019 View Incentives');
    EB.clickthrough('Grand_Cherokee 2019 Vehicle Homepage');
    EB.clickthrough('Grand_Cherokee 2019 Search Inventory');
    EB.clickthrough('Grand_Cherokee 2019 Find a Dealer');
    EB.clickthrough('Grand_Cherokee 2019 View Gallery');
    EB.clickthrough('Renegade 2019 Build and Price');
    EB.clickthrough('Renegade 2019 View Incentives');
    EB.clickthrough('Renegade 2019 Vehicle Homepage');
    EB.clickthrough('Renegade 2019 Search Inventory');
    EB.clickthrough('Renegade 2019 Find a Dealer');
    EB.clickthrough('Renegade 2019 View Gallery');
  	EB.clickthrough('Wrangler 2019 Build and Price');
  	EB.clickthrough('Wrangler 2019 View Incentives');
  	EB.clickthrough('Wrangler 2019 Vehicle Homepage');
  	EB.clickthrough('Wrangler 2019 Search Inventory');
  	EB.clickthrough('Wrangler 2019 Find a Dealer');
    EB.clickthrough('Wrangler 2019 View Gallery');
  	EB.clickthrough('Wrangler_Unlimited 2019 Build and Price');
  	EB.clickthrough('Wrangler_Unlimited 2019 View Incentives');
  	EB.clickthrough('Wrangler_Unlimited 2019 Vehicle Homepage');
  	EB.clickthrough('Wrangler_Unlimited 2019 Search Inventory');
  	EB.clickthrough('Wrangler_Unlimited 2019 Find a Dealer');
    EB.clickthrough('Wrangler_Unlimited 2019 View Gallery');
    EB.clickthrough('Cherokee 2017 Build and Price Background');
    EB.clickthrough('Cherokee 2017 View Incentives Background');
    EB.clickthrough('Cherokee 2017 Vehicle Homepage Background');
    EB.clickthrough('Cherokee 2017 Search Inventory Background');
    EB.clickthrough('Cherokee 2017 Find a Dealer Background');
    EB.clickthrough('Cherokee 2017 View Gallery Background');
    EB.clickthrough('Cherokee 2018 Build and Price Background');
    EB.clickthrough('Cherokee 2018 View Incentives Background');
    EB.clickthrough('Cherokee 2018 Vehicle Homepage Background');
    EB.clickthrough('Cherokee 2018 Search Inventory Background');
    EB.clickthrough('Cherokee 2018 Find a Dealer Background');
    EB.clickthrough('Cherokee 2018 View Gallery Background');
    EB.clickthrough('Cherokee 2019 Build and Price Background');
    EB.clickthrough('Cherokee 2019 View Incentives Background');
    EB.clickthrough('Cherokee 2019 Vehicle Homepage Background');
    EB.clickthrough('Cherokee 2019 Search Inventory Background');
    EB.clickthrough('Cherokee 2019 Find a Dealer Background');
    EB.clickthrough('Cherokee 2019 View Gallery Background');
    EB.clickthrough('Compass 2017 Build and Price Background');
    EB.clickthrough('Compass 2017 View Incentives Background');
    EB.clickthrough('Compass 2017 Vehicle Homepage Background');
    EB.clickthrough('Compass 2017 Search Inventory Background');
    EB.clickthrough('Compass 2017 Find a Dealer Background');
    EB.clickthrough('Compass 2017 View Gallery Background');
    EB.clickthrough('Compass 2018 Build and Price Background');
    EB.clickthrough('Compass 2018 View Incentives Background');
    EB.clickthrough('Compass 2018 Vehicle Homepage Background');
    EB.clickthrough('Compass 2018 Search Inventory Background');
    EB.clickthrough('Compass 2018 Find a Dealer Background');
    EB.clickthrough('Compass 2018 View Gallery Background');
    EB.clickthrough('Compass 2019 Build and Price Background');
    EB.clickthrough('Compass 2019 View Incentives Background');
    EB.clickthrough('Compass 2019 Vehicle Homepage Background');
    EB.clickthrough('Compass 2019 Search Inventory Background');
    EB.clickthrough('Compass 2019 Find a Dealer Background');
    EB.clickthrough('Compass 2019 View Gallery Background');
    EB.clickthrough('Grand_Cherokee 2017 Build and Price Background');
    EB.clickthrough('Grand_Cherokee 2017 View Incentives Background');
    EB.clickthrough('Grand_Cherokee 2017 Vehicle Homepage Background');
    EB.clickthrough('Grand_Cherokee 2017 Search Inventory Background');
    EB.clickthrough('Grand_Cherokee 2017 Find a Dealer Background');
    EB.clickthrough('Grand_Cherokee 2017 View Gallery Background');
    EB.clickthrough('Grand_Cherokee 2018 Build and Price Background');
    EB.clickthrough('Grand_Cherokee 2018 View Incentives Background');
    EB.clickthrough('Grand_Cherokee 2018 Vehicle Homepage Background');
    EB.clickthrough('Grand_Cherokee 2018 Search Inventory Background');
    EB.clickthrough('Grand_Cherokee 2018 Find a Dealer Background');
    EB.clickthrough('Grand_Cherokee 2018 View Gallery Background');
    EB.clickthrough('Grand_Cherokee 2019 Build and Price Background');
    EB.clickthrough('Grand_Cherokee 2019 View Incentives Background');
    EB.clickthrough('Grand_Cherokee 2019 Vehicle Homepage Background');
    EB.clickthrough('Grand_Cherokee 2019 Search Inventory Background');
    EB.clickthrough('Grand_Cherokee 2019 Find a Dealer Background');
    EB.clickthrough('Grand_Cherokee 2019 View Gallery Background');
    EB.clickthrough('Renegade 2017 Build and Price Background');
    EB.clickthrough('Renegade 2017 View Incentives Background');
    EB.clickthrough('Renegade 2017 Vehicle Homepage Background');
    EB.clickthrough('Renegade 2017 Search Inventory Background');
    EB.clickthrough('Renegade 2017 Find a Dealer Background');
    EB.clickthrough('Renegade 2017 View Gallery Background');
    EB.clickthrough('Renegade 2018 Build and Price Background');
    EB.clickthrough('Renegade 2018 View Incentives Background');
    EB.clickthrough('Renegade 2018 Vehicle Homepage Background');
    EB.clickthrough('Renegade 2018 Search Inventory Background');
    EB.clickthrough('Renegade 2018 Find a Dealer Background');
    EB.clickthrough('Renegade 2018 View Gallery Background');
    EB.clickthrough('Renegade 2019 Build and Price Background');
    EB.clickthrough('Renegade 2019 View Incentives Background');
    EB.clickthrough('Renegade 2019 Vehicle Homepage Background');
    EB.clickthrough('Renegade 2019 Search Inventory Background');
    EB.clickthrough('Renegade 2019 Find a Dealer Background');
    EB.clickthrough('Renegade 2019 View Gallery Background');
    EB.clickthrough('Wrangler 2017 Build and Price Background');
    EB.clickthrough('Wrangler 2017 View Incentives Background');
    EB.clickthrough('Wrangler 2017 Vehicle Homepage Background');
    EB.clickthrough('Wrangler 2017 Search Inventory Background');
    EB.clickthrough('Wrangler 2017 Find a Dealer Background');
    EB.clickthrough('Wrangler 2017 View Gallery Background');
    EB.clickthrough('Wrangler 2018 Build and Price Background');
    EB.clickthrough('Wrangler 2018 View Incentives Background');
    EB.clickthrough('Wrangler 2018 Vehicle Homepage Background');
    EB.clickthrough('Wrangler 2018 Search Inventory Background');
    EB.clickthrough('Wrangler 2018 Find a Dealer Background');
    EB.clickthrough('Wrangler 2018 View Gallery Background');
    EB.clickthrough('Wrangler 2019 Build and Price Background');
    EB.clickthrough('Wrangler 2019 View Incentives Background');
    EB.clickthrough('Wrangler 2019 Vehicle Homepage Background');
    EB.clickthrough('Wrangler 2019 Search Inventory Background');
    EB.clickthrough('Wrangler 2019 Find a Dealer Background');
    EB.clickthrough('Wrangler 2019 View Gallery Background');
    EB.clickthrough('Wrangler_Unlimited 2017 Build and Price Background');
    EB.clickthrough('Wrangler_Unlimited 2017 View Incentives Background');
    EB.clickthrough('Wrangler_Unlimited 2017 Vehicle Homepage Background');
    EB.clickthrough('Wrangler_Unlimited 2017 Search Inventory Background');
    EB.clickthrough('Wrangler_Unlimited 2017 Find a Dealer Background');
    EB.clickthrough('Wrangler_Unlimited 2017 View Gallery Background');
    EB.clickthrough('Wrangler_Unlimited 2018 Build and Price Background');
    EB.clickthrough('Wrangler_Unlimited 2018 View Incentives Background');
    EB.clickthrough('Wrangler_Unlimited 2018 Vehicle Homepage Background');
    EB.clickthrough('Wrangler_Unlimited 2018 Search Inventory Background');
    EB.clickthrough('Wrangler_Unlimited 2018 Find a Dealer Background');
    EB.clickthrough('Wrangler_Unlimited 2018 View Gallery Background');
    EB.clickthrough('Wrangler_Unlimited 2019 Build and Price Background');
    EB.clickthrough('Wrangler_Unlimited 2019 View Incentives Background');
    EB.clickthrough('Wrangler_Unlimited 2019 Vehicle Homepage Background');
    EB.clickthrough('Wrangler_Unlimited 2019 Search Inventory Background');
    EB.clickthrough('Wrangler_Unlimited 2019 Find a Dealer Background');
    EB.clickthrough('Wrangler_Unlimited 2019 View Gallery Background');
    EB.clickthrough('Grand Cherokee 2018 Get a Quote');
    EB.clickthrough('Grand Cherokee 2018 Get a Quote Background');
    EB.clickthrough('Grand Cherokee 2019 Get a Quote');
    EB.clickthrough('Grand Cherokee 2019 Get a Quote Background');
	}
//////////////////////////////////
